core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('my_videos/', views.index, name='index')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('', include("video.urls")),
    path('', include("dashboard.urls")),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('videos/', views.videos, name='videos'),
]

core/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

video/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Video(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=200)
    video = models.FileField(upload_to="videos/", default='default_video.mp4')
    category = models.ForeignKey(Category, related_name='videos', on_delete=models.CASCADE, default=1)
    created_by = models.ForeignKey(User, related_name='video', on_delete=models.CASCADE,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    like = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def increment_likes(self):
        if self.like:
            self.like += 1
            self.save()

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

video/forms.py
from django.forms import ModelForm
from .models import Video
from django import forms

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewVideoForm(ModelForm):
    class Meta:
        model= Video
        fields= ['name','description','video']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'video': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditVideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['name', 'description', 'video']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'video': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render, redirect
from video.models import Video
from .forms import SignupForm, LoginForm
from django.contrib.auth import logout

def index(request):
    videos = Video.objects.all()
    return render(request, 'core/index.html', {'videos': videos})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('/login/')

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from video.models import Video

@login_required
def index(request):
    videos = Video.objects.filter(created_by=request.user)
    return render(request, 'dashboard/index.html', {'videos': videos})

video/views.py
from django.shortcuts import render, get_object_or_404
from .models import Video, Category
from django.contrib.auth.decorators import login_required
from .forms import NewVideoForm, EditVideoForm


def videos(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    videos = Video.objects.all()

    if category_id:
        videos = videos.filter(category_id=category_id)

    if query:
        videos = videos.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'video/videos.html', {
        'videos': videos,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    video = get_object_or_404(Video, pk=pk)
    related_videos = Video.objects.filter(category=video.category).exclude(pk=pk)[0:3]
    return render(request, 'video/detail.html', {'video': video, 'related_videos': related_videos})

@login_required
def new(request):
    if request.method == 'POST':
        form = NewVideoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = NewVideoForm()

    return render(request, 'video/form.html', {'form': form})

@login_required
def delete(request, pk):
    video = get_object_or_404(Video, pk=pk, created_by=request.user)
    video.delete()
    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    if request.method == 'POST':
        form = EditVideoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = EditVideoForm()

    return render(request, 'video/form.html', {'form': form})

core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | VBlast</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-4xl font-semibold">VBlast</a>

            <div class="space-x-6">
                <a href="{%url 'video:new'%}" class="text-lg font-semibold hover:text-gray-500">New video</a>
                <a href="{%url 'video:videos'%}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-violet-500 text-white rounded-xl hover:bg-violet-700">Inbox</a>
                    <a href="{%url 'dashboard:index'%}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My Videos</a>
                    <a href="{%url 'core:logout'%}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
                {% else %}
                    <a href="{%url 'core:signup'%}" class="px-6 py-3 text-lg font-semibold bg-violet-500 text-white rounded-xl hover:bg-violet-700">Sign up</a>
                    <a href="{%url 'core:login'%}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500"></p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-violet-500 hover:text-violet-700">About</a></li>
                    <li><a href="#" class="text-lg text-violet-500 hover:text-violet-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-violet-500 hover:text-violet-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-violet-500 hover:text-violet-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/index.html
{%extends 'core/base.html'%}

{% block title %}Index{% endblock %}

{%block content%}
<div class="mt-6 px-6 py-12 bg-violet-300 rounded-xl">
<h2 class="mb-12 text-3xl text-center">Newest Videos</h2>
    <div class="grid grid-cols-3 gap-3">
        {%for video in videos%}
        <div>
            <a href="{%url 'video:detail' video.id %}">
                <div class="transition duration-500 hover:scale-125 hover:bg-white-600 flex justify-center items-center rounded-xl">
                  <video controls="controls" class="rounded-t-xl">
                    <source src="{{ video.video.url }}" type="video/mp4"/>
                  </video>
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{video.name}}</h2>
                </div>
            </a>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

core/templates/core/login.html
{% extends 'core/base.html' %}

{%block content%}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl text-center">
  <h1 class="mb-6 text-3xl">Log in</h1>
  <form method="post" action=".">
    {%csrf_token%}

    {{form.non_field_errors}}
    <div class="mb-3">
    <label class="inline-block mb-2" for="id_username">Username</label><br>
    {{ form.username }}
</div>
<div class="mb-3">
    <label class="inline-block mb-2" for="id_password">Password</label><br>
    {{ form.password }}
</div>
    {%if form.errors or form.non_field_errors%}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {%for field in form%}
      {{field.errors}}
      {%endfor%}
      {{form.non_field_errors}}
    </div>
    {%endif%}
    <button class="py-4 px-8 text-lg bg-violet-500 hover:bg-violet-700 rounded-xl text-white">Submit</button>
  </form>
</div>
{%endblock%}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{%block title%}Sign up{%endblock%}
{%block content%}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl text-center">
  <h1 class="mb-6 text-3xl">Sign up</h1>
  <form method="post" action=".">
    {%csrf_token%}

    {{form.non_field_errors}}
    <div class="mb-3">
      <label class="inline-block mb-2">Username</label><br>
      {{form.username}}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Email</label><br>
      {{form.email}}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Password</label><br>
      {{form.password1}}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Password(again)</label><br>
      {{form.password2}}
    </div>

    {%if form.errors or form.non_field_errors%}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {%for field in form%}
      {{field.errors}}
      {%endfor%}
      {{form.non_field_errors}}
    </div>
    {%endif%}
    <button class="py-4 px-8 text-lg bg-violet-500 hover:bg-violet-700 rounded-xl text-white">Submit</button>
  </form>
</div>
{%endblock%}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}

{%block content%}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
<h2 class="mb-12 text-2xl text-center">My videos</h2>
    <div class="grid grid-cols-3 gap-3">
        {%for video in videos%}
        <div>
            <a href="{%url 'video:detail' video.id %}">
                <div class="transition duration-500 hover:scale-125 hover:bg-white-600 flex justify-center items-center rounded-xl">
                  <video controls="controls" class="rounded-t-xl">
                    <source src="{{ video.video.url }}" type="video/mp4"/>
                  </video>
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{video.name}}</h2>
                </div>
            </a>
        </div>
        {%endfor%}
    </div>
</div>
{% endblock %}

video/templates/video/detail.html
{%extends 'core/base.html'%}

{%block content%}
<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3">
    <video controls="controls" class="mt-6 rounded-t-xl">
        <source src="{{ video.video.url }}" type="video/mp4"/>
    </video>
  </div>
  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{video.name}}</h1>
    <p class="text-gray-500"><strong>Category:</strong>{{video.category}}</p>
    <p class="text-gray-500"><strong>Created by:</strong>{{video.created_by.username}}</p>
    {%if video.description%}
    <p class="text-gray-500"><strong>Description:</strong><br>
            {{video.description}}</p>
    {%endif%}
      {%if request.user == video.created_by%}
      <div class="mt-6 p-6 bg-white rounded-xl">
          <p>Delete this video</p>
          <a href="{%url 'video:edit' video.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-violet-500 rounded-xl">Edit</a>
          <a href="{%url 'video:delete' video.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 rounded-xl">Delete</a>
  </div>
      {%else%}
    <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-violet-500 text-white">Contact Creator</a>
  {%endif%}
  </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
<h2 class="mb-12 text-2xl text-center">Related videos</h2>
    <div class="grid grid-cols-3 gap-3">
        {%for video in related_videos%}
        <div>
            <a href="{%url 'video:detail' video.id%}">
                <div>
                <div class="transition duration-500 hover:scale-125 hover:bg-white-600 flex justify-center items-center rounded-xl">
                  <video controls="controls" class="rounded-t-xl">
                    <source src="{{ video.video.url }}" type="video/mp4"/>
                  </video>
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{video.name}}</h2>
                </div>
        </div>
            </a>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

video/templates/video/form.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="mb-6 text-3xl">New video</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

video/templates/video/videos.html
{% extends 'core/base.html' %}

{% block title %}Videos{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'video:videos' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find your favorite video">

                <button class="mt-2 py-4 px-8 text-lg bg-violet-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'video:videos' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'video:videos' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
                </li>
            </ul>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for video in videos %}
                    <div>
                        <a href="{% url 'video:detail' video.id %}">
                            <div class="transition duration-500 hover:scale-125 hover:bg-white-600 flex justify-center items-center rounded-xl">
                  <video controls="controls" class="rounded-t-xl">
                    <source src="{{ video.video.url }}" type="video/mp4"/>
                  </video>
                </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ video.name }}</h2>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}